//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Res.rc
//
#define IDD_DIALOG_MAIN                 101
#define IDD_DIALOG_ABOUT                102
#define IDD_DIALOG_PE                   106
#define IDD_DIALOG_SECTIONTABLE         107
#define IDD_DIALOG_DIRCTION             108
#define IDD_DIALOG_EXPORTTABLE          110
#define IDD_DIALOG_IMPORTTABLE          112
#define IDD_DIALOG_RESOURCETABLE        113
#define IDD_DIALOG_BASERELOC            114
#define IDD_DIALOG_BOUNDIMPORT          115
#define IDD_DIALOG_IAT                  116
#define IDD_DIALOG_DLL_THREAD           118
#define IDD_DIALOG_DLL_IMPORT           119
#define IDC_BUTTON_PE                   1001
#define IDC_BUTTON_ABOUT                1002
#define IDC_BUTTON_QUIT                 1003
#define IDC_LIST_PROCESS                1004
#define IDC_LIST_MOUDLE                 1005
#define IDC_STATIC_SPECIFICATION        1006
#define IDC_BUTTON_SHELL                1006
#define IDC_BUTTON_PE_CLOSE             1007
#define IDC_BUTTON_DLL_INJECT_REMOTE_THREAD 1007
#define IDC_BUTTON_PE_SECTIONS          1008
#define IDC_BUTTON_DLL_INJECT_IMPORT_TABLE 1008
#define IDC_BUTTON_PE_DIRECTION         1009
#define IDC_EDIT1                       1010
#define IDC_EDIT_1                      1010
#define IDC_EDIT_RESOURCETABLE          1010
#define IDC_EDIT_PROCESS                1010
#define IDC_EDIT_DIRECTION_IMPORT_RVA   1011
#define IDC_EDIT_DIRECTION_R2           1011
#define IDC_EDIT_DLL_IMPORT             1011
#define IDC_EDIT2                       1013
#define IDC_EDIT_2                      1013
#define IDC_EDIT3                       1016
#define IDC_EDIT_4                      1016
#define IDC_EDIT4                       1017
#define IDC_EDIT_6                      1017
#define IDC_EDIT5                       1018
#define IDC_EDIT_8                      1018
#define IDC_EDIT6                       1019
#define IDC_EDIT_7                      1019
#define IDC_EDIT7                       1020
#define IDC_EDIT_5                      1020
#define IDC_EDIT8                       1021
#define IDC_EDIT_3                      1021
#define IDC_EDIT9                       1022
#define IDC_EDIT_9                      1022
#define IDC_EDIT10                      1023
#define IDC_EDIT_10                     1023
#define IDC_EDIT11                      1024
#define IDC_EDIT_11                     1024
#define IDC_EDIT12                      1025
#define IDC_EDIT_12                     1025
#define IDC_EDIT13                      1026
#define IDC_EDIT_13                     1026
#define IDC_EDIT14                      1027
#define IDC_EDIT_14                     1027
#define IDC_EDIT15                      1028
#define IDC_EDIT_15                     1028
#define IDC_EDIT16                      1029
#define IDC_EDIT_16                     1029
#define IDC_LIST_SECTIONTABLE           1032
#define IDC_EDIT_DIRECTION_EXPORT_RVA   1033
#define IDC_EDIT_DIRECTION_R1           1033
#define IDC_EDIT_DIRECTION_RESOURCE_RVA 1034
#define IDC_EDIT_DIRECTION_R3           1034
#define IDC_BUTTON_DIRECTION_OUTPORT    1035
#define IDC_BUTTON_DIRECTION_CLOSE      1036
#define IDC_EDIT_EXPORTTABLE            1037
#define IDC_EDIT_BASERELOC              1038
#define IDC_EDIT_BOUNDIMPORT            1039
#define IDC_EDIT_IAT                    1040
#define IDC_EDIT_IMPORTTABLE            1041
#define IDC_EDIT_DIRECTION_EXPORT_SIZE  1042
#define IDC_EDIT_DIRECTION_S1           1042
#define IDC_EDIT_DIRECTION_IMPORT_SIZE  1043
#define IDC_EDIT_DIRECTION_S2           1043
#define IDC_BUTTON_DLL_FILE_SELECTION_IMPORT 1043
#define IDC_EDIT_DIRECTION_RESOURCE_SIZE 1044
#define IDC_EDIT_DIRECTION_S3           1044
#define IDC_BUTTON_DLL_SECETION_IMPORT  1044
#define IDC_EDIT_DIRECTION_EXCEPTION_RVA 1045
#define IDC_EDIT_DIRECTION_R4           1045
#define IDC_BUTTON_DLL_SELECTION        1045
#define IDC_BUTTON_IMPORT_OK            1045
#define IDC_EDIT_DIRECTION_SECURITY_RVA 1046
#define IDC_EDIT_DIRECTION_R5           1046
#define IDC_BUTTON_IMPORT_QUIT          1046
#define IDC_EDIT_DIRECTION_BASERELOC_RVA 1047
#define IDC_EDIT_DIRECTION_R6           1047
#define IDC_EDIT_DLL_REMOTETHREAD       1047
#define IDC_EDIT_DIRECTION_EXCEPTION_SIZE 1048
#define IDC_EDIT_DIRECTION_S4           1048
#define IDC_EDIT_DLL_FILE_IMPORT        1048
#define IDC_BUTTON_THREAD_OK            1048
#define IDC_EDIT_DIRECTION_SECURITY_SIZE 1049
#define IDC_EDIT_DIRECTION_S5           1049
#define IDC_BUTTON_THREAD_QUIT          1049
#define IDC_EDIT_DIRECTION_BASERELOC_SIZE 1050
#define IDC_EDIT_DIRECTION_S6           1050
#define IDC_EDIT_DIRECTION_DEBUG_RVA    1051
#define IDC_EDIT_DIRECTION_R7           1051
#define IDC_EDIT_DIRECTION_COPYRIGHT_RVA 1052
#define IDC_EDIT_DIRECTION_R8           1052
#define IDC_EDIT_DIRECTION_GLOBALPTR_RVA 1053
#define IDC_EDIT_DIRECTION_R9           1053
#define IDC_EDIT_DIRECTION_DEBUG_SIZE   1054
#define IDC_EDIT_DIRECTION_S7           1054
#define IDC_EDIT_DIRECTION_COPYRIGHT_SIZE 1055
#define IDC_EDIT_DIRECTION_S8           1055
#define IDC_EDIT_DIRECTION_GLOBALPTR_SIZE 1056
#define IDC_EDIT_DIRECTION_S9           1056
#define IDC_EDIT_DIRECTION_TLS_RVA      1057
#define IDC_EDIT_DIRECTION_R10          1057
#define IDC_EDIT_DIRECTION_LOADCONFIG_RVA 1058
#define IDC_EDIT_DIRECTION_R11          1058
#define IDC_EDIT_DIRECTION_BOUNDIMPORT_RVA 1059
#define IDC_EDIT_DIRECTION_R12          1059
#define IDC_EDIT_DIRECTION_TLS_SIZE     1060
#define IDC_EDIT_DIRECTION_S10          1060
#define IDC_EDIT_DIRECTION_LOADCONFIG_SIZE 1061
#define IDC_EDIT_DIRECTION_S11          1061
#define IDC_EDIT_DIRECTION_BOUNDIMPORT_SIZE 1062
#define IDC_EDIT_DIRECTION_S12          1062
#define IDC_EDIT_DIRECTION_IAT_RVA      1063
#define IDC_EDIT_DIRECTION_R13          1063
#define IDC_EDIT_DIRECTION_DELAYIMPORT_RVA 1064
#define IDC_EDIT_DIRECTION_R14          1064
#define IDC_EDIT_DIRECTION_COM_RVA      1065
#define IDC_EDIT_DIRECTION_R15          1065
#define IDC_EDIT_DIRECTION_IAT_SIZE     1066
#define IDC_EDIT_DIRECTION_S13          1066
#define IDC_EDIT_DIRECTION_DELAYIMPORT_SIZE 1067
#define IDC_EDIT_DIRECTION_S14          1067
#define IDC_EDIT_DIRECTION_COM_SIZE     1068
#define IDC_EDIT_DIRECTION_S15          1068
#define IDC_EDIT_DIRECTION_SAVE_RVA     1069
#define IDC_EDIT_DIRECTION_R16          1069
#define IDC_EDIT_DIRECTION_SAVE_SIZE    1070
#define IDC_EDIT_DIRECTION_S16          1070
#define IDC_BUTTON_DIRECTION_IMPORT     1071
#define IDC_BUTTON_DIRECTION_RESOURCETABLE 1072
#define IDC_BUTTON_DIRECTION_BASERELOC  1073
#define IDC_BUTTON_DIRECTION_BOUNDIMPORT 1074
#define IDC_BUTTON_DIRECTION_IAT        1075

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
